# Generated by Django 2.2.3 on 2019-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_reviews',
            fields=[
                ('rid', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('rhead', models.CharField(max_length=100)),
                ('star', models.IntegerField(max_length=1)),
            ],
        ),
    ]
