# Generated by Django 2.2.3 on 2019-08-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0002_product_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_reviews',
            new_name='productreviews',
        ),
    ]
