# Generated by Django 2.2.3 on 2019-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0004_listing_p_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='data',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
