# Generated by Django 2.2.3 on 2019-08-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productlist', '0005_productreviews_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='cid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreviews',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productlist.listing'),
            preserve_default=False,
        ),
    ]
