# Generated by Django 2.2.3 on 2019-08-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0007_auto_20190820_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='product',
            new_name='id',
        ),
    ]
