# Generated by Django 2.2.3 on 2019-08-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0015_addcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addcart',
        ),
    ]
