# Generated by Django 2.2.3 on 2019-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0016_delete_addcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotdeals',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=10)),
                ('price', models.IntegerField(max_length=100)),
                ('oldprice', models.IntegerField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('p_specification', models.TextField(max_length=600)),
                ('p_color', models.CharField(max_length=100)),
                ('mainphoto', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
