# Generated by Django 2.2.3 on 2019-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customerbillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='zipcode',
            field=models.IntegerField(max_length=10),
        ),
    ]
