# Generated by Django 2.2.3 on 2019-09-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190926_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
